Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = 1024
    vb.cpus = 1
  end

  vms = [
    { name: "ubuntu1", ip: "192.168.56.101" },
    { name: "ubuntu2", ip: "192.168.56.102" }
  ]

  vms.each do |vm|
    config.vm.define vm[:name] do |node|
      node.vm.hostname = vm[:name]
      node.vm.network "private_network", ip: vm[:ip]

      node.vm.provision "shell", inline: <<-SHELL
        echo "PasswordAuthentication yes" | sudo tee /etc/ssh/sshd_config.d/01-password-auth.conf
        echo "vagrant:vagrant" | sudo chpasswd
        sudo systemctl restart sshd
      SHELL

      node.vm.provider "virtualbox" do |vb|
        vb.name = "#{vm[:name]}_VM"
      end
    end
  end
end