---
- name: Create Ansible User
  hosts: all
  become: yes

  vars:
    ansible_user_name: ansible
    ansible_user_shell: /bin/bash
    local_ssh_key_directory: ~/.ssh/

  tasks:
    - name: Ensure ansible user exists
      user:
        name: "{{ ansible_user_name }}"
        shell: "{{ ansible_user_shell }}"
        state: present
    
    - name: Grant passwordless sudo access via sudoers.d
      copy:
        dest: "/etc/sudoers.d/{{ ansible_user_name }}"
        content: "{{ ansible_user_name }} ALL=(ALL) NOPASSWD: ALL\n"
        mode: '0440'
        validate: 'visudo -cf %s'

    - name: Ensure .ssh directory exists for new ansible user
      file:
        path: "/home/{{ ansible_user_name }}/.ssh"
        state: directory
        owner: "{{ ansible_user_name }}"
        group: "{{ ansible_user_name }}"
        mode: '0700'

    - name: Copy public keys to the remote
      authorized_key:
        key: "{{ lookup('file', item) }}"
        user: "{{ ansible_user_name }}"
      loop: "{{ query('fileglob', local_ssh_key_directory + '*.pub') }}"
