/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AuthIndexRouteImport } from './routes/_auth/index'
import { Route as AuthUserDashboardRouteImport } from './routes/_auth/user-dashboard'
import { Route as AuthSettingsRouteImport } from './routes/_auth/settings'
import { Route as AuthMapRouteImport } from './routes/_auth/map'
import { Route as AuthImportExportRouteImport } from './routes/_auth/import-export'
import { Route as AuthDocsRouteImport } from './routes/_auth/docs'
import { Route as AuthAddItemsRouteImport } from './routes/_auth/add-items'
import { Route as AuthUsersIndexRouteImport } from './routes/_auth/users/index'
import { Route as AuthTeamsIndexRouteImport } from './routes/_auth/teams/index'
import { Route as AuthLabsIndexRouteImport } from './routes/_auth/labs/index'
import { Route as AuthInventoryIndexRouteImport } from './routes/_auth/inventory/index'
import { Route as AuthHistoryIndexRouteImport } from './routes/_auth/history/index'
import { Route as AuthDocsIndexRouteImport } from './routes/_auth/docs/index'
import { Route as AuthUsersUserIdRouteImport } from './routes/_auth/users/$userId'
import { Route as AuthTeamsTeamIdRouteImport } from './routes/_auth/teams/$teamId'
import { Route as AuthMachinesMachineIdRouteImport } from './routes/_auth/machines/$machineId'
import { Route as AuthLabsLabIdRouteImport } from './routes/_auth/labs/$labId'
import { Route as AuthInventoryInventoryIdRouteImport } from './routes/_auth/inventory/$inventoryId'
import { Route as AuthHistoryHistoryIdRouteImport } from './routes/_auth/history/$historyId'
import { Route as AuthDocsDocIdRouteImport } from './routes/_auth/docs/$docId'
import { Route as AuthAdminPanelUsersRouteImport } from './routes/_auth/admin-panel/users'
import { Route as AuthAdminPanelTeamsRouteImport } from './routes/_auth/admin-panel/teams'
import { Route as AuthAdminPanelMachinesRouteImport } from './routes/_auth/admin-panel/machines'
import { Route as AuthAdminPanelLoggingRouteImport } from './routes/_auth/admin-panel/logging'
import { Route as AuthAdminPanelInventoryRouteImport } from './routes/_auth/admin-panel/inventory'
import { Route as AuthInventoryDeviceDeviceidRouteImport } from './routes/_auth/inventory/device/$deviceid'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthUserDashboardRoute = AuthUserDashboardRouteImport.update({
  id: '/user-dashboard',
  path: '/user-dashboard',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSettingsRoute = AuthSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthRoute,
} as any)
const AuthMapRoute = AuthMapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => AuthRoute,
} as any)
const AuthImportExportRoute = AuthImportExportRouteImport.update({
  id: '/import-export',
  path: '/import-export',
  getParentRoute: () => AuthRoute,
} as any)
const AuthDocsRoute = AuthDocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAddItemsRoute = AuthAddItemsRouteImport.update({
  id: '/add-items',
  path: '/add-items',
  getParentRoute: () => AuthRoute,
} as any)
const AuthUsersIndexRoute = AuthUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthTeamsIndexRoute = AuthTeamsIndexRouteImport.update({
  id: '/teams/',
  path: '/teams/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLabsIndexRoute = AuthLabsIndexRouteImport.update({
  id: '/labs/',
  path: '/labs/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthInventoryIndexRoute = AuthInventoryIndexRouteImport.update({
  id: '/inventory/',
  path: '/inventory/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthHistoryIndexRoute = AuthHistoryIndexRouteImport.update({
  id: '/history/',
  path: '/history/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthDocsIndexRoute = AuthDocsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthDocsRoute,
} as any)
const AuthUsersUserIdRoute = AuthUsersUserIdRouteImport.update({
  id: '/users/$userId',
  path: '/users/$userId',
  getParentRoute: () => AuthRoute,
} as any)
const AuthTeamsTeamIdRoute = AuthTeamsTeamIdRouteImport.update({
  id: '/teams/$teamId',
  path: '/teams/$teamId',
  getParentRoute: () => AuthRoute,
} as any)
const AuthMachinesMachineIdRoute = AuthMachinesMachineIdRouteImport.update({
  id: '/machines/$machineId',
  path: '/machines/$machineId',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLabsLabIdRoute = AuthLabsLabIdRouteImport.update({
  id: '/labs/$labId',
  path: '/labs/$labId',
  getParentRoute: () => AuthRoute,
} as any)
const AuthInventoryInventoryIdRoute =
  AuthInventoryInventoryIdRouteImport.update({
    id: '/inventory/$inventoryId',
    path: '/inventory/$inventoryId',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthHistoryHistoryIdRoute = AuthHistoryHistoryIdRouteImport.update({
  id: '/history/$historyId',
  path: '/history/$historyId',
  getParentRoute: () => AuthRoute,
} as any)
const AuthDocsDocIdRoute = AuthDocsDocIdRouteImport.update({
  id: '/$docId',
  path: '/$docId',
  getParentRoute: () => AuthDocsRoute,
} as any)
const AuthAdminPanelUsersRoute = AuthAdminPanelUsersRouteImport.update({
  id: '/admin-panel/users',
  path: '/admin-panel/users',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAdminPanelTeamsRoute = AuthAdminPanelTeamsRouteImport.update({
  id: '/admin-panel/teams',
  path: '/admin-panel/teams',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAdminPanelMachinesRoute = AuthAdminPanelMachinesRouteImport.update({
  id: '/admin-panel/machines',
  path: '/admin-panel/machines',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAdminPanelLoggingRoute = AuthAdminPanelLoggingRouteImport.update({
  id: '/admin-panel/logging',
  path: '/admin-panel/logging',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAdminPanelInventoryRoute = AuthAdminPanelInventoryRouteImport.update({
  id: '/admin-panel/inventory',
  path: '/admin-panel/inventory',
  getParentRoute: () => AuthRoute,
} as any)
const AuthInventoryDeviceDeviceidRoute =
  AuthInventoryDeviceDeviceidRouteImport.update({
    id: '/inventory/device/$deviceid',
    path: '/inventory/device/$deviceid',
    getParentRoute: () => AuthRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthIndexRoute
  '/login': typeof LoginRoute
  '/add-items': typeof AuthAddItemsRoute
  '/docs': typeof AuthDocsRouteWithChildren
  '/import-export': typeof AuthImportExportRoute
  '/map': typeof AuthMapRoute
  '/settings': typeof AuthSettingsRoute
  '/user-dashboard': typeof AuthUserDashboardRoute
  '/admin-panel/inventory': typeof AuthAdminPanelInventoryRoute
  '/admin-panel/logging': typeof AuthAdminPanelLoggingRoute
  '/admin-panel/machines': typeof AuthAdminPanelMachinesRoute
  '/admin-panel/teams': typeof AuthAdminPanelTeamsRoute
  '/admin-panel/users': typeof AuthAdminPanelUsersRoute
  '/docs/$docId': typeof AuthDocsDocIdRoute
  '/history/$historyId': typeof AuthHistoryHistoryIdRoute
  '/inventory/$inventoryId': typeof AuthInventoryInventoryIdRoute
  '/labs/$labId': typeof AuthLabsLabIdRoute
  '/machines/$machineId': typeof AuthMachinesMachineIdRoute
  '/teams/$teamId': typeof AuthTeamsTeamIdRoute
  '/users/$userId': typeof AuthUsersUserIdRoute
  '/docs/': typeof AuthDocsIndexRoute
  '/history/': typeof AuthHistoryIndexRoute
  '/inventory/': typeof AuthInventoryIndexRoute
  '/labs/': typeof AuthLabsIndexRoute
  '/teams/': typeof AuthTeamsIndexRoute
  '/users/': typeof AuthUsersIndexRoute
  '/inventory/device/$deviceid': typeof AuthInventoryDeviceDeviceidRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/add-items': typeof AuthAddItemsRoute
  '/import-export': typeof AuthImportExportRoute
  '/map': typeof AuthMapRoute
  '/settings': typeof AuthSettingsRoute
  '/user-dashboard': typeof AuthUserDashboardRoute
  '/': typeof AuthIndexRoute
  '/admin-panel/inventory': typeof AuthAdminPanelInventoryRoute
  '/admin-panel/logging': typeof AuthAdminPanelLoggingRoute
  '/admin-panel/machines': typeof AuthAdminPanelMachinesRoute
  '/admin-panel/teams': typeof AuthAdminPanelTeamsRoute
  '/admin-panel/users': typeof AuthAdminPanelUsersRoute
  '/docs/$docId': typeof AuthDocsDocIdRoute
  '/history/$historyId': typeof AuthHistoryHistoryIdRoute
  '/inventory/$inventoryId': typeof AuthInventoryInventoryIdRoute
  '/labs/$labId': typeof AuthLabsLabIdRoute
  '/machines/$machineId': typeof AuthMachinesMachineIdRoute
  '/teams/$teamId': typeof AuthTeamsTeamIdRoute
  '/users/$userId': typeof AuthUsersUserIdRoute
  '/docs': typeof AuthDocsIndexRoute
  '/history': typeof AuthHistoryIndexRoute
  '/inventory': typeof AuthInventoryIndexRoute
  '/labs': typeof AuthLabsIndexRoute
  '/teams': typeof AuthTeamsIndexRoute
  '/users': typeof AuthUsersIndexRoute
  '/inventory/device/$deviceid': typeof AuthInventoryDeviceDeviceidRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/login': typeof LoginRoute
  '/_auth/add-items': typeof AuthAddItemsRoute
  '/_auth/docs': typeof AuthDocsRouteWithChildren
  '/_auth/import-export': typeof AuthImportExportRoute
  '/_auth/map': typeof AuthMapRoute
  '/_auth/settings': typeof AuthSettingsRoute
  '/_auth/user-dashboard': typeof AuthUserDashboardRoute
  '/_auth/': typeof AuthIndexRoute
  '/_auth/admin-panel/inventory': typeof AuthAdminPanelInventoryRoute
  '/_auth/admin-panel/logging': typeof AuthAdminPanelLoggingRoute
  '/_auth/admin-panel/machines': typeof AuthAdminPanelMachinesRoute
  '/_auth/admin-panel/teams': typeof AuthAdminPanelTeamsRoute
  '/_auth/admin-panel/users': typeof AuthAdminPanelUsersRoute
  '/_auth/docs/$docId': typeof AuthDocsDocIdRoute
  '/_auth/history/$historyId': typeof AuthHistoryHistoryIdRoute
  '/_auth/inventory/$inventoryId': typeof AuthInventoryInventoryIdRoute
  '/_auth/labs/$labId': typeof AuthLabsLabIdRoute
  '/_auth/machines/$machineId': typeof AuthMachinesMachineIdRoute
  '/_auth/teams/$teamId': typeof AuthTeamsTeamIdRoute
  '/_auth/users/$userId': typeof AuthUsersUserIdRoute
  '/_auth/docs/': typeof AuthDocsIndexRoute
  '/_auth/history/': typeof AuthHistoryIndexRoute
  '/_auth/inventory/': typeof AuthInventoryIndexRoute
  '/_auth/labs/': typeof AuthLabsIndexRoute
  '/_auth/teams/': typeof AuthTeamsIndexRoute
  '/_auth/users/': typeof AuthUsersIndexRoute
  '/_auth/inventory/device/$deviceid': typeof AuthInventoryDeviceDeviceidRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/add-items'
    | '/docs'
    | '/import-export'
    | '/map'
    | '/settings'
    | '/user-dashboard'
    | '/admin-panel/inventory'
    | '/admin-panel/logging'
    | '/admin-panel/machines'
    | '/admin-panel/teams'
    | '/admin-panel/users'
    | '/docs/$docId'
    | '/history/$historyId'
    | '/inventory/$inventoryId'
    | '/labs/$labId'
    | '/machines/$machineId'
    | '/teams/$teamId'
    | '/users/$userId'
    | '/docs/'
    | '/history/'
    | '/inventory/'
    | '/labs/'
    | '/teams/'
    | '/users/'
    | '/inventory/device/$deviceid'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/add-items'
    | '/import-export'
    | '/map'
    | '/settings'
    | '/user-dashboard'
    | '/'
    | '/admin-panel/inventory'
    | '/admin-panel/logging'
    | '/admin-panel/machines'
    | '/admin-panel/teams'
    | '/admin-panel/users'
    | '/docs/$docId'
    | '/history/$historyId'
    | '/inventory/$inventoryId'
    | '/labs/$labId'
    | '/machines/$machineId'
    | '/teams/$teamId'
    | '/users/$userId'
    | '/docs'
    | '/history'
    | '/inventory'
    | '/labs'
    | '/teams'
    | '/users'
    | '/inventory/device/$deviceid'
  id:
    | '__root__'
    | '/_auth'
    | '/login'
    | '/_auth/add-items'
    | '/_auth/docs'
    | '/_auth/import-export'
    | '/_auth/map'
    | '/_auth/settings'
    | '/_auth/user-dashboard'
    | '/_auth/'
    | '/_auth/admin-panel/inventory'
    | '/_auth/admin-panel/logging'
    | '/_auth/admin-panel/machines'
    | '/_auth/admin-panel/teams'
    | '/_auth/admin-panel/users'
    | '/_auth/docs/$docId'
    | '/_auth/history/$historyId'
    | '/_auth/inventory/$inventoryId'
    | '/_auth/labs/$labId'
    | '/_auth/machines/$machineId'
    | '/_auth/teams/$teamId'
    | '/_auth/users/$userId'
    | '/_auth/docs/'
    | '/_auth/history/'
    | '/_auth/inventory/'
    | '/_auth/labs/'
    | '/_auth/teams/'
    | '/_auth/users/'
    | '/_auth/inventory/device/$deviceid'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/': {
      id: '/_auth/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/user-dashboard': {
      id: '/_auth/user-dashboard'
      path: '/user-dashboard'
      fullPath: '/user-dashboard'
      preLoaderRoute: typeof AuthUserDashboardRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/settings': {
      id: '/_auth/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthSettingsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/map': {
      id: '/_auth/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof AuthMapRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/import-export': {
      id: '/_auth/import-export'
      path: '/import-export'
      fullPath: '/import-export'
      preLoaderRoute: typeof AuthImportExportRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/docs': {
      id: '/_auth/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof AuthDocsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/add-items': {
      id: '/_auth/add-items'
      path: '/add-items'
      fullPath: '/add-items'
      preLoaderRoute: typeof AuthAddItemsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/users/': {
      id: '/_auth/users/'
      path: '/users'
      fullPath: '/users/'
      preLoaderRoute: typeof AuthUsersIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/teams/': {
      id: '/_auth/teams/'
      path: '/teams'
      fullPath: '/teams/'
      preLoaderRoute: typeof AuthTeamsIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/labs/': {
      id: '/_auth/labs/'
      path: '/labs'
      fullPath: '/labs/'
      preLoaderRoute: typeof AuthLabsIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/inventory/': {
      id: '/_auth/inventory/'
      path: '/inventory'
      fullPath: '/inventory/'
      preLoaderRoute: typeof AuthInventoryIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/history/': {
      id: '/_auth/history/'
      path: '/history'
      fullPath: '/history/'
      preLoaderRoute: typeof AuthHistoryIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/docs/': {
      id: '/_auth/docs/'
      path: '/'
      fullPath: '/docs/'
      preLoaderRoute: typeof AuthDocsIndexRouteImport
      parentRoute: typeof AuthDocsRoute
    }
    '/_auth/users/$userId': {
      id: '/_auth/users/$userId'
      path: '/users/$userId'
      fullPath: '/users/$userId'
      preLoaderRoute: typeof AuthUsersUserIdRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/teams/$teamId': {
      id: '/_auth/teams/$teamId'
      path: '/teams/$teamId'
      fullPath: '/teams/$teamId'
      preLoaderRoute: typeof AuthTeamsTeamIdRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/machines/$machineId': {
      id: '/_auth/machines/$machineId'
      path: '/machines/$machineId'
      fullPath: '/machines/$machineId'
      preLoaderRoute: typeof AuthMachinesMachineIdRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/labs/$labId': {
      id: '/_auth/labs/$labId'
      path: '/labs/$labId'
      fullPath: '/labs/$labId'
      preLoaderRoute: typeof AuthLabsLabIdRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/inventory/$inventoryId': {
      id: '/_auth/inventory/$inventoryId'
      path: '/inventory/$inventoryId'
      fullPath: '/inventory/$inventoryId'
      preLoaderRoute: typeof AuthInventoryInventoryIdRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/history/$historyId': {
      id: '/_auth/history/$historyId'
      path: '/history/$historyId'
      fullPath: '/history/$historyId'
      preLoaderRoute: typeof AuthHistoryHistoryIdRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/docs/$docId': {
      id: '/_auth/docs/$docId'
      path: '/$docId'
      fullPath: '/docs/$docId'
      preLoaderRoute: typeof AuthDocsDocIdRouteImport
      parentRoute: typeof AuthDocsRoute
    }
    '/_auth/admin-panel/users': {
      id: '/_auth/admin-panel/users'
      path: '/admin-panel/users'
      fullPath: '/admin-panel/users'
      preLoaderRoute: typeof AuthAdminPanelUsersRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/admin-panel/teams': {
      id: '/_auth/admin-panel/teams'
      path: '/admin-panel/teams'
      fullPath: '/admin-panel/teams'
      preLoaderRoute: typeof AuthAdminPanelTeamsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/admin-panel/machines': {
      id: '/_auth/admin-panel/machines'
      path: '/admin-panel/machines'
      fullPath: '/admin-panel/machines'
      preLoaderRoute: typeof AuthAdminPanelMachinesRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/admin-panel/logging': {
      id: '/_auth/admin-panel/logging'
      path: '/admin-panel/logging'
      fullPath: '/admin-panel/logging'
      preLoaderRoute: typeof AuthAdminPanelLoggingRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/admin-panel/inventory': {
      id: '/_auth/admin-panel/inventory'
      path: '/admin-panel/inventory'
      fullPath: '/admin-panel/inventory'
      preLoaderRoute: typeof AuthAdminPanelInventoryRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/inventory/device/$deviceid': {
      id: '/_auth/inventory/device/$deviceid'
      path: '/inventory/device/$deviceid'
      fullPath: '/inventory/device/$deviceid'
      preLoaderRoute: typeof AuthInventoryDeviceDeviceidRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface AuthDocsRouteChildren {
  AuthDocsDocIdRoute: typeof AuthDocsDocIdRoute
  AuthDocsIndexRoute: typeof AuthDocsIndexRoute
}

const AuthDocsRouteChildren: AuthDocsRouteChildren = {
  AuthDocsDocIdRoute: AuthDocsDocIdRoute,
  AuthDocsIndexRoute: AuthDocsIndexRoute,
}

const AuthDocsRouteWithChildren = AuthDocsRoute._addFileChildren(
  AuthDocsRouteChildren,
)

interface AuthRouteChildren {
  AuthAddItemsRoute: typeof AuthAddItemsRoute
  AuthDocsRoute: typeof AuthDocsRouteWithChildren
  AuthImportExportRoute: typeof AuthImportExportRoute
  AuthMapRoute: typeof AuthMapRoute
  AuthSettingsRoute: typeof AuthSettingsRoute
  AuthUserDashboardRoute: typeof AuthUserDashboardRoute
  AuthIndexRoute: typeof AuthIndexRoute
  AuthAdminPanelInventoryRoute: typeof AuthAdminPanelInventoryRoute
  AuthAdminPanelLoggingRoute: typeof AuthAdminPanelLoggingRoute
  AuthAdminPanelMachinesRoute: typeof AuthAdminPanelMachinesRoute
  AuthAdminPanelTeamsRoute: typeof AuthAdminPanelTeamsRoute
  AuthAdminPanelUsersRoute: typeof AuthAdminPanelUsersRoute
  AuthHistoryHistoryIdRoute: typeof AuthHistoryHistoryIdRoute
  AuthInventoryInventoryIdRoute: typeof AuthInventoryInventoryIdRoute
  AuthLabsLabIdRoute: typeof AuthLabsLabIdRoute
  AuthMachinesMachineIdRoute: typeof AuthMachinesMachineIdRoute
  AuthTeamsTeamIdRoute: typeof AuthTeamsTeamIdRoute
  AuthUsersUserIdRoute: typeof AuthUsersUserIdRoute
  AuthHistoryIndexRoute: typeof AuthHistoryIndexRoute
  AuthInventoryIndexRoute: typeof AuthInventoryIndexRoute
  AuthLabsIndexRoute: typeof AuthLabsIndexRoute
  AuthTeamsIndexRoute: typeof AuthTeamsIndexRoute
  AuthUsersIndexRoute: typeof AuthUsersIndexRoute
  AuthInventoryDeviceDeviceidRoute: typeof AuthInventoryDeviceDeviceidRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthAddItemsRoute: AuthAddItemsRoute,
  AuthDocsRoute: AuthDocsRouteWithChildren,
  AuthImportExportRoute: AuthImportExportRoute,
  AuthMapRoute: AuthMapRoute,
  AuthSettingsRoute: AuthSettingsRoute,
  AuthUserDashboardRoute: AuthUserDashboardRoute,
  AuthIndexRoute: AuthIndexRoute,
  AuthAdminPanelInventoryRoute: AuthAdminPanelInventoryRoute,
  AuthAdminPanelLoggingRoute: AuthAdminPanelLoggingRoute,
  AuthAdminPanelMachinesRoute: AuthAdminPanelMachinesRoute,
  AuthAdminPanelTeamsRoute: AuthAdminPanelTeamsRoute,
  AuthAdminPanelUsersRoute: AuthAdminPanelUsersRoute,
  AuthHistoryHistoryIdRoute: AuthHistoryHistoryIdRoute,
  AuthInventoryInventoryIdRoute: AuthInventoryInventoryIdRoute,
  AuthLabsLabIdRoute: AuthLabsLabIdRoute,
  AuthMachinesMachineIdRoute: AuthMachinesMachineIdRoute,
  AuthTeamsTeamIdRoute: AuthTeamsTeamIdRoute,
  AuthUsersUserIdRoute: AuthUsersUserIdRoute,
  AuthHistoryIndexRoute: AuthHistoryIndexRoute,
  AuthInventoryIndexRoute: AuthInventoryIndexRoute,
  AuthLabsIndexRoute: AuthLabsIndexRoute,
  AuthTeamsIndexRoute: AuthTeamsIndexRoute,
  AuthUsersIndexRoute: AuthUsersIndexRoute,
  AuthInventoryDeviceDeviceidRoute: AuthInventoryDeviceDeviceidRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
