[pytest]
markers =
    integration: marks tests as integration tests
    unit: marks tests as unit tests
    smoke: marks tests as smoke tests
    database: marks tests as database tests
    api: marks tests as api tests
    prometheus: marks tests as prometheus tests
    ansible: marks tests as ansible tests
    rbac: mark tests using role based access control
    security: mark tests using security features
    legacy: deprecated tests that should be removed in the future

asyncio_mode = auto
asyncio_default_test_loop_scope = session
asyncio_default_fixture_loop_scope = session