name: CI E2E Tests Action
on:
  workflow_call:
jobs:
    test-e2e:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v5
            - name: Build application
              run: docker compose up -d
            - name: Run E2E test
              run: |
                docker compose exec api pytest --html=report.html --self-contained-html
            - name: Save report
              uses: actions/upload-artifact@v7
              with:
                name: report
                path: |
                  report.html


