name: CI Main Workflow
on:
  pull_request:
    branches:
      - main
jobs:
    ci-api:
        uses: ./.github/workflows/ci-api.yaml
    ci-frontend:
        uses: ./.github/workflows/ci-frontend.yaml
    ci-e2e:
        uses: ./.github/workflows/ci-e2e.yaml
